// Code generated by MockGen. DO NOT EDIT.
// Source: credential_service.go
//
// Generated by this command:
//
//	mockgen -source=credential_service.go -destination=../mocks/credential_mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCredentialServiceInterface is a mock of CredentialServiceInterface interface.
type MockCredentialServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockCredentialServiceInterfaceMockRecorder is the mock recorder for MockCredentialServiceInterface.
type MockCredentialServiceInterfaceMockRecorder struct {
	mock *MockCredentialServiceInterface
}

// NewMockCredentialServiceInterface creates a new mock instance.
func NewMockCredentialServiceInterface(ctrl *gomock.Controller) *MockCredentialServiceInterface {
	mock := &MockCredentialServiceInterface{ctrl: ctrl}
	mock.recorder = &MockCredentialServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialServiceInterface) EXPECT() *MockCredentialServiceInterfaceMockRecorder {
	return m.recorder
}

// DeleteOfficerCredentials mocks base method.
func (m *MockCredentialServiceInterface) DeleteOfficerCredentials(ctx context.Context, officerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOfficerCredentials", ctx, officerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOfficerCredentials indicates an expected call of DeleteOfficerCredentials.
func (mr *MockCredentialServiceInterfaceMockRecorder) DeleteOfficerCredentials(ctx, officerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOfficerCredentials", reflect.TypeOf((*MockCredentialServiceInterface)(nil).DeleteOfficerCredentials), ctx, officerID)
}

// DeleteResidentCredentials mocks base method.
func (m *MockCredentialServiceInterface) DeleteResidentCredentials(ctx context.Context, residentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteResidentCredentials", ctx, residentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteResidentCredentials indicates an expected call of DeleteResidentCredentials.
func (mr *MockCredentialServiceInterfaceMockRecorder) DeleteResidentCredentials(ctx, residentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteResidentCredentials", reflect.TypeOf((*MockCredentialServiceInterface)(nil).DeleteResidentCredentials), ctx, residentID)
}
