// Code generated by MockGen. DO NOT EDIT.
// Source: feedback_service.go
//
// Generated by this command:
//
//	mockgen -source=feedback_service.go -destination=../mocks/feedback_mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/MananLed/majorProjectSMS/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockFeedbackServiceInterface is a mock of FeedbackServiceInterface interface.
type MockFeedbackServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockFeedbackServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockFeedbackServiceInterfaceMockRecorder is the mock recorder for MockFeedbackServiceInterface.
type MockFeedbackServiceInterfaceMockRecorder struct {
	mock *MockFeedbackServiceInterface
}

// NewMockFeedbackServiceInterface creates a new mock instance.
func NewMockFeedbackServiceInterface(ctrl *gomock.Controller) *MockFeedbackServiceInterface {
	mock := &MockFeedbackServiceInterface{ctrl: ctrl}
	mock.recorder = &MockFeedbackServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedbackServiceInterface) EXPECT() *MockFeedbackServiceInterfaceMockRecorder {
	return m.recorder
}

// GetFeedbackByID mocks base method.
func (m *MockFeedbackServiceInterface) GetFeedbackByID(id string) ([]model.Feedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeedbackByID", id)
	ret0, _ := ret[0].([]model.Feedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeedbackByID indicates an expected call of GetFeedbackByID.
func (mr *MockFeedbackServiceInterfaceMockRecorder) GetFeedbackByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeedbackByID", reflect.TypeOf((*MockFeedbackServiceInterface)(nil).GetFeedbackByID), id)
}

// GetFeedbacks mocks base method.
func (m *MockFeedbackServiceInterface) GetFeedbacks() ([]model.Feedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeedbacks")
	ret0, _ := ret[0].([]model.Feedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeedbacks indicates an expected call of GetFeedbacks.
func (mr *MockFeedbackServiceInterfaceMockRecorder) GetFeedbacks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeedbacks", reflect.TypeOf((*MockFeedbackServiceInterface)(nil).GetFeedbacks))
}

// IssueFeedback mocks base method.
func (m *MockFeedbackServiceInterface) IssueFeedback(content, residentID, flat string, rating int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueFeedback", content, residentID, flat, rating)
	ret0, _ := ret[0].(error)
	return ret0
}

// IssueFeedback indicates an expected call of IssueFeedback.
func (mr *MockFeedbackServiceInterfaceMockRecorder) IssueFeedback(content, residentID, flat, rating any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueFeedback", reflect.TypeOf((*MockFeedbackServiceInterface)(nil).IssueFeedback), content, residentID, flat, rating)
}
