// Code generated by MockGen. DO NOT EDIT.
// Source: invoice_service.go
//
// Generated by this command:
//
//	mockgen -source=invoice_service.go -destination=../mocks/invoice_mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	model "github.com/MananLed/majorProjectSMS/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockInvoiceServiceInterface is a mock of InvoiceServiceInterface interface.
type MockInvoiceServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInvoiceServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockInvoiceServiceInterfaceMockRecorder is the mock recorder for MockInvoiceServiceInterface.
type MockInvoiceServiceInterfaceMockRecorder struct {
	mock *MockInvoiceServiceInterface
}

// NewMockInvoiceServiceInterface creates a new mock instance.
func NewMockInvoiceServiceInterface(ctrl *gomock.Controller) *MockInvoiceServiceInterface {
	mock := &MockInvoiceServiceInterface{ctrl: ctrl}
	mock.recorder = &MockInvoiceServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvoiceServiceInterface) EXPECT() *MockInvoiceServiceInterfaceMockRecorder {
	return m.recorder
}

// GenerateInvoice mocks base method.
func (m *MockInvoiceServiceInterface) GenerateInvoice(amount float64, month time.Month, year int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateInvoice", amount, month, year)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateInvoice indicates an expected call of GenerateInvoice.
func (mr *MockInvoiceServiceInterfaceMockRecorder) GenerateInvoice(amount, month, year any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateInvoice", reflect.TypeOf((*MockInvoiceServiceInterface)(nil).GenerateInvoice), amount, month, year)
}

// GetInvoiceByMonthAndYear mocks base method.
func (m *MockInvoiceServiceInterface) GetInvoiceByMonthAndYear(month time.Month, year int) (*model.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoiceByMonthAndYear", month, year)
	ret0, _ := ret[0].(*model.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoiceByMonthAndYear indicates an expected call of GetInvoiceByMonthAndYear.
func (mr *MockInvoiceServiceInterfaceMockRecorder) GetInvoiceByMonthAndYear(month, year any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoiceByMonthAndYear", reflect.TypeOf((*MockInvoiceServiceInterface)(nil).GetInvoiceByMonthAndYear), month, year)
}

// GetInvoicesByYear mocks base method.
func (m *MockInvoiceServiceInterface) GetInvoicesByYear(year int) ([]model.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoicesByYear", year)
	ret0, _ := ret[0].([]model.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvoicesByYear indicates an expected call of GetInvoicesByYear.
func (mr *MockInvoiceServiceInterfaceMockRecorder) GetInvoicesByYear(year any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoicesByYear", reflect.TypeOf((*MockInvoiceServiceInterface)(nil).GetInvoicesByYear), year)
}
