// Code generated by MockGen. DO NOT EDIT.
// Source: notice_service.go
//
// Generated by this command:
//
//	mockgen -source=notice_service.go -destination=../mocks/notice_mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	model "github.com/MananLed/majorProjectSMS/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockNoticeServiceInterface is a mock of NoticeServiceInterface interface.
type MockNoticeServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNoticeServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockNoticeServiceInterfaceMockRecorder is the mock recorder for MockNoticeServiceInterface.
type MockNoticeServiceInterfaceMockRecorder struct {
	mock *MockNoticeServiceInterface
}

// NewMockNoticeServiceInterface creates a new mock instance.
func NewMockNoticeServiceInterface(ctrl *gomock.Controller) *MockNoticeServiceInterface {
	mock := &MockNoticeServiceInterface{ctrl: ctrl}
	mock.recorder = &MockNoticeServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNoticeServiceInterface) EXPECT() *MockNoticeServiceInterfaceMockRecorder {
	return m.recorder
}

// GetNotices mocks base method.
func (m *MockNoticeServiceInterface) GetNotices() ([]model.Notice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotices")
	ret0, _ := ret[0].([]model.Notice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotices indicates an expected call of GetNotices.
func (mr *MockNoticeServiceInterfaceMockRecorder) GetNotices() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotices", reflect.TypeOf((*MockNoticeServiceInterface)(nil).GetNotices))
}

// GetNoticesByMonthYear mocks base method.
func (m *MockNoticeServiceInterface) GetNoticesByMonthYear(month time.Month, year int) ([]model.Notice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNoticesByMonthYear", month, year)
	ret0, _ := ret[0].([]model.Notice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNoticesByMonthYear indicates an expected call of GetNoticesByMonthYear.
func (mr *MockNoticeServiceInterfaceMockRecorder) GetNoticesByMonthYear(month, year any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNoticesByMonthYear", reflect.TypeOf((*MockNoticeServiceInterface)(nil).GetNoticesByMonthYear), month, year)
}

// GetNoticesByYear mocks base method.
func (m *MockNoticeServiceInterface) GetNoticesByYear(year int) ([]model.Notice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNoticesByYear", year)
	ret0, _ := ret[0].([]model.Notice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNoticesByYear indicates an expected call of GetNoticesByYear.
func (mr *MockNoticeServiceInterfaceMockRecorder) GetNoticesByYear(year any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNoticesByYear", reflect.TypeOf((*MockNoticeServiceInterface)(nil).GetNoticesByYear), year)
}

// IssueNotice mocks base method.
func (m *MockNoticeServiceInterface) IssueNotice(content string, month time.Month, year int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueNotice", content, month, year)
	ret0, _ := ret[0].(error)
	return ret0
}

// IssueNotice indicates an expected call of IssueNotice.
func (mr *MockNoticeServiceInterfaceMockRecorder) IssueNotice(content, month, year any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueNotice", reflect.TypeOf((*MockNoticeServiceInterface)(nil).IssueNotice), content, month, year)
}
