// Code generated by MockGen. DO NOT EDIT.
// Source: service_request_service.go
//
// Generated by this command:
//
//	mockgen -source=service_request_service.go -destination=../mocks/service_request_mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/MananLed/majorProjectSMS/internal/model"
	utils "github.com/MananLed/majorProjectSMS/internal/utils"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceRequestServiceInterface is a mock of ServiceRequestServiceInterface interface.
type MockServiceRequestServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceRequestServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockServiceRequestServiceInterfaceMockRecorder is the mock recorder for MockServiceRequestServiceInterface.
type MockServiceRequestServiceInterfaceMockRecorder struct {
	mock *MockServiceRequestServiceInterface
}

// NewMockServiceRequestServiceInterface creates a new mock instance.
func NewMockServiceRequestServiceInterface(ctrl *gomock.Controller) *MockServiceRequestServiceInterface {
	mock := &MockServiceRequestServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceRequestServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceRequestServiceInterface) EXPECT() *MockServiceRequestServiceInterfaceMockRecorder {
	return m.recorder
}

// ApproveServiceRequest mocks base method.
func (m *MockServiceRequestServiceInterface) ApproveServiceRequest(requestID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveServiceRequest", requestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveServiceRequest indicates an expected call of ApproveServiceRequest.
func (mr *MockServiceRequestServiceInterfaceMockRecorder) ApproveServiceRequest(requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveServiceRequest", reflect.TypeOf((*MockServiceRequestServiceInterface)(nil).ApproveServiceRequest), requestID)
}

// BookServiceRequest mocks base method.
func (m *MockServiceRequestServiceInterface) BookServiceRequest(req model.ServiceRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BookServiceRequest", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// BookServiceRequest indicates an expected call of BookServiceRequest.
func (mr *MockServiceRequestServiceInterfaceMockRecorder) BookServiceRequest(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BookServiceRequest", reflect.TypeOf((*MockServiceRequestServiceInterface)(nil).BookServiceRequest), req)
}

// CancelServiceRequest mocks base method.
func (m *MockServiceRequestServiceInterface) CancelServiceRequest(userID string, requestID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelServiceRequest", userID, requestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelServiceRequest indicates an expected call of CancelServiceRequest.
func (mr *MockServiceRequestServiceInterfaceMockRecorder) CancelServiceRequest(userID, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelServiceRequest", reflect.TypeOf((*MockServiceRequestServiceInterface)(nil).CancelServiceRequest), userID, requestID)
}

// DeleteServiceRequestByID mocks base method.
func (m *MockServiceRequestServiceInterface) DeleteServiceRequestByID(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServiceRequestByID", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServiceRequestByID indicates an expected call of DeleteServiceRequestByID.
func (mr *MockServiceRequestServiceInterfaceMockRecorder) DeleteServiceRequestByID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServiceRequestByID", reflect.TypeOf((*MockServiceRequestServiceInterface)(nil).DeleteServiceRequestByID), ctx)
}

// GetApprovedRequestsByServiceType mocks base method.
func (m *MockServiceRequestServiceInterface) GetApprovedRequestsByServiceType(serviceType model.ServiceType) []model.ServiceRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApprovedRequestsByServiceType", serviceType)
	ret0, _ := ret[0].([]model.ServiceRequest)
	return ret0
}

// GetApprovedRequestsByServiceType indicates an expected call of GetApprovedRequestsByServiceType.
func (mr *MockServiceRequestServiceInterfaceMockRecorder) GetApprovedRequestsByServiceType(serviceType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApprovedRequestsByServiceType", reflect.TypeOf((*MockServiceRequestServiceInterface)(nil).GetApprovedRequestsByServiceType), serviceType)
}

// GetAvailableTimeSlots mocks base method.
func (m *MockServiceRequestServiceInterface) GetAvailableTimeSlots(service model.ServiceType) []utils.TimeSlot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableTimeSlots", service)
	ret0, _ := ret[0].([]utils.TimeSlot)
	return ret0
}

// GetAvailableTimeSlots indicates an expected call of GetAvailableTimeSlots.
func (mr *MockServiceRequestServiceInterfaceMockRecorder) GetAvailableTimeSlots(service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableTimeSlots", reflect.TypeOf((*MockServiceRequestServiceInterface)(nil).GetAvailableTimeSlots), service)
}

// GetPendingRequestsByServiceType mocks base method.
func (m *MockServiceRequestServiceInterface) GetPendingRequestsByServiceType(serviceType model.ServiceType) []model.ServiceRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingRequestsByServiceType", serviceType)
	ret0, _ := ret[0].([]model.ServiceRequest)
	return ret0
}

// GetPendingRequestsByServiceType indicates an expected call of GetPendingRequestsByServiceType.
func (mr *MockServiceRequestServiceInterfaceMockRecorder) GetPendingRequestsByServiceType(serviceType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingRequestsByServiceType", reflect.TypeOf((*MockServiceRequestServiceInterface)(nil).GetPendingRequestsByServiceType), serviceType)
}

// GetServiceRequestsByStatus mocks base method.
func (m *MockServiceRequestServiceInterface) GetServiceRequestsByStatus(userID string, status model.Status) []model.ServiceRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceRequestsByStatus", userID, status)
	ret0, _ := ret[0].([]model.ServiceRequest)
	return ret0
}

// GetServiceRequestsByStatus indicates an expected call of GetServiceRequestsByStatus.
func (mr *MockServiceRequestServiceInterfaceMockRecorder) GetServiceRequestsByStatus(userID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceRequestsByStatus", reflect.TypeOf((*MockServiceRequestServiceInterface)(nil).GetServiceRequestsByStatus), userID, status)
}

// GetServiceTypeByID mocks base method.
func (m *MockServiceRequestServiceInterface) GetServiceTypeByID(requestID uuid.UUID) (model.ServiceType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceTypeByID", requestID)
	ret0, _ := ret[0].(model.ServiceType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceTypeByID indicates an expected call of GetServiceTypeByID.
func (mr *MockServiceRequestServiceInterfaceMockRecorder) GetServiceTypeByID(requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceTypeByID", reflect.TypeOf((*MockServiceRequestServiceInterface)(nil).GetServiceTypeByID), requestID)
}

// RescheduleServiceRequest mocks base method.
func (m *MockServiceRequestServiceInterface) RescheduleServiceRequest(userID string, requestID uuid.UUID, newSlot utils.TimeSlot, newService model.ServiceType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RescheduleServiceRequest", userID, requestID, newSlot, newService)
	ret0, _ := ret[0].(error)
	return ret0
}

// RescheduleServiceRequest indicates an expected call of RescheduleServiceRequest.
func (mr *MockServiceRequestServiceInterfaceMockRecorder) RescheduleServiceRequest(userID, requestID, newSlot, newService any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RescheduleServiceRequest", reflect.TypeOf((*MockServiceRequestServiceInterface)(nil).RescheduleServiceRequest), userID, requestID, newSlot, newService)
}
