// Code generated by MockGen. DO NOT EDIT.
// Source: society_service.go
//
// Generated by this command:
//
//	mockgen -source=society_service.go -destination=../mocks/society_mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/MananLed/majorProjectSMS/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockSocietyServiceInterface is a mock of SocietyServiceInterface interface.
type MockSocietyServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSocietyServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockSocietyServiceInterfaceMockRecorder is the mock recorder for MockSocietyServiceInterface.
type MockSocietyServiceInterfaceMockRecorder struct {
	mock *MockSocietyServiceInterface
}

// NewMockSocietyServiceInterface creates a new mock instance.
func NewMockSocietyServiceInterface(ctrl *gomock.Controller) *MockSocietyServiceInterface {
	mock := &MockSocietyServiceInterface{ctrl: ctrl}
	mock.recorder = &MockSocietyServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSocietyServiceInterface) EXPECT() *MockSocietyServiceInterfaceMockRecorder {
	return m.recorder
}

// GetAllOfficers mocks base method.
func (m *MockSocietyServiceInterface) GetAllOfficers(ctx context.Context) ([]model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOfficers", ctx)
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllOfficers indicates an expected call of GetAllOfficers.
func (mr *MockSocietyServiceInterfaceMockRecorder) GetAllOfficers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOfficers", reflect.TypeOf((*MockSocietyServiceInterface)(nil).GetAllOfficers), ctx)
}

// GetAllResidents mocks base method.
func (m *MockSocietyServiceInterface) GetAllResidents(ctx context.Context) ([]model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllResidents", ctx)
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllResidents indicates an expected call of GetAllResidents.
func (mr *MockSocietyServiceInterfaceMockRecorder) GetAllResidents(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllResidents", reflect.TypeOf((*MockSocietyServiceInterface)(nil).GetAllResidents), ctx)
}
