Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Architectures:
      - x86_64
    Timeout: 200
    Handler: bootstrap
    Runtime: provided.al2023

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      Cors: 
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS,PATCH'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  Login:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/aws-functions/login
      Events:
        ApiEvent:
          Type: Api 
          Properties:
            Method: post 
            Path: /login 
            RestApiId: !Ref Api 

  Signup:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x 
    Properties:
      CodeUri: ./cmd/aws-functions/signup
      Events:
        ApiEvent:
          Type: Api 
          Properties: 
            Method: post 
            Path: /signup 
            RestApiId: !Ref Api

  Profile:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/aws-functions/profile
      Events:
        ApiEvent:
          Type: Api 
          Properties:
            Method: get 
            Path: /profile
            RestApiId: !Ref Api

  ViewResident:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/aws-functions/view_residents
      Events:
        ApiEvent:
          Type: Api 
          Properties:
            Method: get 
            Path: /society/residents
            RestApiId: !Ref Api

  ViewOfficers:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/aws-functions/view_officers
      Events:
        ApiEvent:
          Type: Api 
          Properties:
            Method: get 
            Path: /society/officers
            RestApiId: !Ref Api

  ViewNotices:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/aws-functions/view_all_notices
      Events:
        ApiEvent:
          Type: Api 
          Properties:
            Method: get 
            Path: /notices
            RestApiId: !Ref Api

  ViewNoticesMonthYear:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/aws-functions/view_notices_month_year
      Events:
        ApiEvent:
          Type: Api 
          Properties:
            Method: get 
            Path: /notices/month-year
            RestApiId: !Ref Api

  ViewInvoicesMonthYear:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: ./cmd/aws-functions/view_invoices_month_year
      Events:
        ApiEvent:
          Type: Api 
          Properties:
            Method: get 
            Path: /invoices/month-year
            RestApiId: !Ref Api

  DeleteOfficer:
    Type: AWS::Serverless::Function 
    Metadata: 
      BuildMethod: go1.x 
    Properties:
      CodeUri: ./cmd/aws-functions/delete_officer
      Events:
        ApiEvent:
          Type: Api 
          Properties:
            Method: delete 
            Path: /credentials/officer
            RestApiId: !Ref Api 

  DeleteResident:
    Type: AWS::Serverless::Function 
    Metadata: 
      BuildMethod: go1.x 
    Properties:
      CodeUri: ./cmd/aws-functions/delete_resident
      Events:
        ApiEvent:
          Type: Api 
          Properties:
            Method: delete 
            Path: /credentials/resident
            RestApiId: !Ref Api 

  IssueNotice:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x 
    Properties:
      CodeUri: ./cmd/aws-functions/issue_notice
      Events:
        ApiEvent:
          Type: Api 
          Properties: 
            Method: post 
            Path: /notices/issue
            RestApiId: !Ref Api

  IssueInvoice:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x 
    Properties:
      CodeUri: ./cmd/aws-functions/issue_invoice
      Events:
        ApiEvent:
          Type: Api 
          Properties: 
            Method: post 
            Path: /invoices/issue
            RestApiId: !Ref Api

  GetAllRequests:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x 
    Properties:
      CodeUri: ./cmd/aws-functions/get_all_requests
      Events:
        ApiEvent:
          Type: Api 
          Properties: 
            Method: get 
            Path: /service/all
            RestApiId: !Ref Api

  GetAllRequestsOfResident:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x 
    Properties:
      CodeUri: ./cmd/aws-functions/get_all_requests_of_resident
      Events:
        ApiEvent:
          Type: Api 
          Properties: 
            Method: get 
            Path: /service/resident/all
            RestApiId: !Ref Api

  GetAvailableTimeSlots:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x 
    Properties:
      CodeUri: ./cmd/aws-functions/get_available_time_slots
      Events:
        ApiEvent:
          Type: Api 
          Properties: 
            Method: get 
            Path: /service/time-slots
            RestApiId: !Ref Api

  OfficerCount:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x 
    Properties:
      CodeUri: ./cmd/aws-functions/officer_count
      Events:
        ApiEvent:
          Type: Api 
          Properties: 
            Method: get 
            Path: /society/officers/count
            RestApiId: !Ref Api

  ResidentCount:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x 
    Properties:
      CodeUri: ./cmd/aws-functions/resident_count
      Events:
        ApiEvent:
          Type: Api 
          Properties: 
            Method: get 
            Path: /society/residents/count
            RestApiId: !Ref Api

  GetRequestsByTypeAndStatus:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x 
    Properties:
      CodeUri: ./cmd/aws-functions/get_request_type_status
      Events:
        ApiEvent:
          Type: Api 
          Properties: 
            Method: get 
            Path: /service/type-status
            RestApiId: !Ref Api

  BookRequest:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x 
    Properties:
      CodeUri: ./cmd/aws-functions/book_request
      Events:
        ApiEvent:
          Type: Api 
          Properties: 
            Method: post
            Path: /service
            RestApiId: !Ref Api

  DeleteRequest:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x 
    Properties:
      CodeUri: ./cmd/aws-functions/delete_request
      Events:
        ApiEvent:
          Type: Api 
          Properties: 
            Method: delete
            Path: /service/cancel/{id}
            RestApiId: !Ref Api

  RescheduleReqeust:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x 
    Properties:
      CodeUri: ./cmd/aws-functions/reschedule_request
      Events:
        ApiEvent:
          Type: Api 
          Properties: 
            Method: patch
            Path: /service/reschedule/{id}
            RestApiId: !Ref Api

  ApproveRequest:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x 
    Properties:
      CodeUri: ./cmd/aws-functions/approve_request
      Events:
        ApiEvent:
          Type: Api 
          Properties: 
            Method: patch
            Path: /service/approve/{id}
            RestApiId: !Ref Api

  CompleteRequest:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x 
    Properties:
      CodeUri: ./cmd/aws-functions/complete_request
      Events:
        ApiEvent:
          Type: Api 
          Properties: 
            Method: patch
            Path: /service/complete/{id}
            RestApiId: !Ref Api

  GetAllFeedbacks:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x 
    Properties:
      CodeUri: ./cmd/aws-functions/get_feedbacks
      Events:
        ApiEvent:
          Type: Api 
          Properties: 
            Method: get
            Path: /feedbacks
            RestApiId: !Ref Api
  