Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Architectures:
    - x86_64
    Timeout: 200
    Handler: bootstrap
    Runtime: provided.al2023
Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      Cors:
        AllowMethods: '''GET,POST,PUT,DELETE,OPTIONS,PATCH'''
        AllowHeaders: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'''
        AllowOrigin: '''*'''
  Login:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: Login
    Properties:
      CodeUri: Login
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /login
            RestApiId:
              Ref: Api
  Signup:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: Signup
    Properties:
      CodeUri: Signup
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /signup
            RestApiId:
              Ref: Api
  Profile:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: Profile
    Properties:
      CodeUri: Profile
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /profile
            RestApiId:
              Ref: Api
  ViewResident:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: ViewResident
    Properties:
      CodeUri: ViewResident
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /society/residents
            RestApiId:
              Ref: Api
  ViewOfficers:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: ViewOfficers
    Properties:
      CodeUri: ViewOfficers
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /society/officers
            RestApiId:
              Ref: Api
  ViewNotices:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: ViewNotices
    Properties:
      CodeUri: ViewNotices
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /notices
            RestApiId:
              Ref: Api
  ViewNoticesMonthYear:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: ViewNoticesMonthYear
    Properties:
      CodeUri: ViewNoticesMonthYear
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /notices/month-year
            RestApiId:
              Ref: Api
  ViewInvoicesMonthYear:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: ViewInvoicesMonthYear
    Properties:
      CodeUri: ViewInvoicesMonthYear
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /invoices/month-year
            RestApiId:
              Ref: Api
  DeleteOfficer:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: DeleteOfficer
    Properties:
      CodeUri: DeleteOfficer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: delete
            Path: /credentials/officer
            RestApiId:
              Ref: Api
  DeleteResident:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: DeleteResident
    Properties:
      CodeUri: DeleteResident
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: delete
            Path: /credentials/resident
            RestApiId:
              Ref: Api
  IssueNotice:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: IssueNotice
    Properties:
      CodeUri: IssueNotice
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /notices/issue
            RestApiId:
              Ref: Api
  IssueInvoice:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: IssueInvoice
    Properties:
      CodeUri: IssueInvoice
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /invoices/issue
            RestApiId:
              Ref: Api
  GetAllRequests:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: GetAllRequests
    Properties:
      CodeUri: GetAllRequests
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /service/all
            RestApiId:
              Ref: Api
  GetAllRequestsOfResident:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: GetAllRequestsOfResident
    Properties:
      CodeUri: GetAllRequestsOfResident
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /service/resident/all
            RestApiId:
              Ref: Api
  GetAvailableTimeSlots:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: GetAvailableTimeSlots
    Properties:
      CodeUri: GetAvailableTimeSlots
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /service/time-slots
            RestApiId:
              Ref: Api
  OfficerCount:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: OfficerCount
    Properties:
      CodeUri: OfficerCount
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /society/officers/count
            RestApiId:
              Ref: Api
  ResidentCount:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: ResidentCount
    Properties:
      CodeUri: ResidentCount
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /society/residents/count
            RestApiId:
              Ref: Api
  GetRequestsByTypeAndStatus:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: GetRequestsByTypeAndStatus
    Properties:
      CodeUri: GetRequestsByTypeAndStatus
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /service/type-status
            RestApiId:
              Ref: Api
  BookRequest:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: BookRequest
    Properties:
      CodeUri: BookRequest
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /service
            RestApiId:
              Ref: Api
  DeleteRequest:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: DeleteRequest
    Properties:
      CodeUri: DeleteRequest
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: delete
            Path: /service/cancel/{id}
            RestApiId:
              Ref: Api
  RescheduleReqeust:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: RescheduleReqeust
    Properties:
      CodeUri: RescheduleReqeust
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: patch
            Path: /service/reschedule/{id}
            RestApiId:
              Ref: Api
  ApproveRequest:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: ApproveRequest
    Properties:
      CodeUri: ApproveRequest
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: patch
            Path: /service/approve/{id}
            RestApiId:
              Ref: Api
  CompleteRequest:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: CompleteRequest
    Properties:
      CodeUri: CompleteRequest
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: patch
            Path: /service/complete/{id}
            RestApiId:
              Ref: Api
  GetAllFeedbacks:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
      SamResourceId: GetAllFeedbacks
    Properties:
      CodeUri: GetAllFeedbacks
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /feedbacks
            RestApiId:
              Ref: Api
